### ISSUE TITLE
Thread locking bug during wifi connection

### ISSUE THREAD

**Issue by mrinc** [TinyWATCH-S3/Official-firmware#1]
As per https://youtu.be/v54gPHlUPQA - there is a 1/2s delay when connecting to the WiFi and getting it's IP.

**Comment by UnexpectedMaker** [comment]
This has been improved/fixed in  https://github.com/TinyWATCH-S3/Official-firmware/commit/8f9d11512a0237fe9accc902c753963303a5d62c

The thread task priority was quite low, and there was a bug with disconnecting the server/wifi disconnect that could hinder new connections.
