### ISSUE TITLE
too many initializer values in display.h

### ISSUE THREAD

**Issue by tetraDB** [TinyWATCH-S3/Official-firmware#37]
When I try to compile the code, I'm getting an error about too many intializer values: -

`
const uint8_t backlight_settings_vbus[3] = {200, 150, 100, 0};
const uint8_t backlight_settings_vbat[3] = {200, 100, 50, 0};
`

Should it be size [4] or not have the ,0 at the end?

https://github.com/TinyWATCH-S3/Official-firmware/blob/139e8ab861037877398dfd8ab7b23b307bf6ab84/Platform-io-source/src/display.h#L83

https://github.com/TinyWATCH-S3/Official-firmware/blob/139e8ab861037877398dfd8ab7b23b307bf6ab84/Platform-io-source/src/display.h#L84

**Comment by UnexpectedMaker** [comment]
Woops, looks like I committed something I was not supposed to. Sorry.

I just pushed the fix, please re-pull.

**Comment by tetraDB** [comment]
Great, thanks!
