### ISSUE TITLE
Compass App N E S W text not being drawn with inclusion of font number

### ISSUE THREAD

**Issue by tetraDB** [TinyWATCH-S3/Official-firmware#38]
https://github.com/TinyWATCH-S3/Official-firmware/blob/0e638292a3be9076e6b20a858e7f92a060403a18/Platform-io-source/src/tw_apps/app_Compass.cpp#L93
https://github.com/TinyWATCH-S3/Official-firmware/blob/0e638292a3be9076e6b20a858e7f92a060403a18/Platform-io-source/src/tw_apps/app_Compass.cpp#L94
https://github.com/TinyWATCH-S3/Official-firmware/blob/0e638292a3be9076e6b20a858e7f92a060403a18/Platform-io-source/src/tw_apps/app_Compass.cpp#L95
https://github.com/TinyWATCH-S3/Official-firmware/blob/0e638292a3be9076e6b20a858e7f92a060403a18/Platform-io-source/src/tw_apps/app_Compass.cpp#L96

removing the ',2)' font number fixes the issue

**Comment by UnexpectedMaker** [comment]
Yeah, this app is so not useful or working right now ;)
I'll fix the font stuff, but this needs a working Magnetometer :(

**Comment by UnexpectedMaker** [comment]
Fixed in https://github.com/TinyWATCH-S3/Official-firmware/commit/13e51cdf9fc0879efb9c6e066d02ddbdb1098692

Thanks for working on the compass app and for taking on working on the magnetometer calibration!
